/**
 * Even Fibonacci numbers
 *
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million,
 * find the sum of the even-valued terms.
 */
public class Problem2 {
    public static int fact(int i, int iNext, int acc, int max) {
        if (iNext >= max) {
            return acc;
        } else {
            if ((iNext % 2) == 0) {
                acc += iNext;
            }
            return fact(iNext, i + iNext, acc, max);
        }
    }

    public static int fibo(int n) {
        int i = 1;
        int sum = 0;

        if (n > 0) {
            sum = fact(i, i + i, sum, n);
        }

        return sum;
    }

    public static void main(String[] args) {
        System.out.println("Sum: "+ Problem2.fibo(4000000));
    }
}
